### ISSUE TITLE
FE - Modal for change user data 

### ISSUE THREAD

**Issue by janmrakava** [prikryla/friendly_betting#33]
I guess I can right now implement modal, which will be the interface to change the data, will not send anything to BE yet though, as there are functions to implement for that.

**Comment by janmrakava** [comment]
I don't know, how to show, that Im working on this issue, so I just leave a comment here- 

In progress :)

**Comment by prikryla** [comment]
Well, you can create a label for WIP or something like that. We can label those issues that we're working on. WDYT?

**Comment by janmrakava** [comment]
I guess we can, great idea mate:)
