### ISSUE TITLE
FE - Feedback after bad credentials for the user

### ISSUE THREAD

**Issue by janmrakava** [prikryla/friendly_betting#5]
Its neccessary to add some feedback for the user, when he enter bad password or username (BE returns error)

**Comment by janmrakava** [comment]
Work start - 13.8.2024

**Comment by prikryla** [comment]
@janmrakava So basically I should add some logic in case of invalid credentials, right? How you would like to handle this? Just some return code with some message or do you have any other idea? I'm not sure if you can handle all of this on FE side... but my login function of the route should return some feedback in case of invalid login.

**Comment by janmrakava** [comment]
This is just FE task I think. Because when user entered bad password for example, BE already return message "Invalid credentials" So Im gonna catch this error and display some feedback for the user 

So I think I don't need anything from you here:)

**Comment by prikryla** [comment]
Cool beans. I wasn't sure how does it work right now. Thanks for the clarification. I should get oriented of the current BE state and do some progress.

**Comment by janmrakava** [comment]
Great idea my code buddy:)
